//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace netcoreFreesql.Models {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class Customers {

		[JsonProperty, Column(DbType = "NCHAR(5)", IsPrimary = true)]
		public string CustomerID { get; set; }

		[JsonProperty, Column(DbType = "NVARCHAR(40)")]
		public string CompanyName { get; set; }

		[JsonProperty, Column(DbType = "NVARCHAR(30)")]
		public string ContactName { get; set; }

		[JsonProperty, Column(DbType = "NVARCHAR(30)")]
		public string ContactTitle { get; set; }

		[JsonProperty, Column(DbType = "NVARCHAR(60)")]
		public string Address { get; set; }

		[JsonProperty, Column(DbType = "NVARCHAR(15)")]
		public string City { get; set; }

		[JsonProperty, Column(DbType = "NVARCHAR(15)")]
		public string Region { get; set; }

		[JsonProperty, Column(DbType = "NVARCHAR(10)")]
		public string PostalCode { get; set; }

		[JsonProperty, Column(DbType = "NVARCHAR(15)")]
		public string Country { get; set; }

		[JsonProperty, Column(DbType = "NVARCHAR(24)")]
		public string Phone { get; set; }

		[JsonProperty, Column(DbType = "NVARCHAR(24)")]
		public string Fax { get; set; }


		#region 外键 => 导航属性，OneToMany

		[Navigate("CustomerID")]
		public virtual List<Orders> Orderss { get; set; }

		#endregion

		#region 外键 => 导航属性，ManyToMany

		#endregion
	}

}
