//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace netcoreFreesql.Models {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class EmployeesTerritories {

		[JsonProperty, Column(IsPrimary = true)]
		public int EmployeeID { get => _EmployeeID; set {
			if (_EmployeeID == value) return;
			_EmployeeID = value;
			Employees = null;
		} }
		private int _EmployeeID;

		[JsonProperty]
		public int TerritoryID { get => _TerritoryID; set {
			if (_TerritoryID == value) return;
			_TerritoryID = value;
			Territories = null;
		} }
		private int _TerritoryID;


		#region 外键 => 导航属性，ManyToOne/OneToOne

		[Navigate("TerritoryID")]
		public virtual Territories Territories { get; set; }

		[Navigate("EmployeeID")]
		public virtual Employees Employees { get; set; }

		#endregion

		#region 外键 => 导航属性，ManyToMany

		#endregion
	}

}
