//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace netcoreFreesql.Models {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class Employees {

		[JsonProperty, Column(IsPrimary = true)]
		public int EmployeeID { get; set; }

		[JsonProperty, Column(DbType = "IMAGE")]
		public string Photo { get; set; }

		[JsonProperty, Column(DbType = "NVARCHAR(4)")]
		public string Extension { get; set; }

		[JsonProperty, Column(DbType = "NVARCHAR(24)")]
		public string HomePhone { get; set; }

		[JsonProperty, Column(DbType = "NVARCHAR(15)")]
		public string Country { get; set; }

		[JsonProperty, Column(DbType = "NVARCHAR(10)")]
		public string PostalCode { get; set; }

		[JsonProperty, Column(DbType = "NVARCHAR(15)")]
		public string Region { get; set; }

		[JsonProperty, Column(DbType = "NTEXT")]
		public string Notes { get; set; }

		[JsonProperty, Column(DbType = "NVARCHAR(15)")]
		public string City { get; set; }

		[JsonProperty]
		public DateTime? HireDate { get; set; }

		[JsonProperty]
		public DateTime? BirthDate { get; set; }

		[JsonProperty, Column(DbType = "NVARCHAR(25)")]
		public string TitleOfCourtesy { get; set; }

		[JsonProperty, Column(DbType = "NVARCHAR(30)")]
		public string Title { get; set; }

		[JsonProperty, Column(DbType = "NVARCHAR(10)")]
		public string FirstName { get; set; }

		[JsonProperty, Column(DbType = "NVARCHAR(20)")]
		public string LastName { get; set; }

		[JsonProperty, Column(DbType = "NVARCHAR(60)")]
		public string Address { get; set; }

		[JsonProperty]
		public string PhotoPath { get; set; }


		#region 外键 => 导航属性，ManyToMany

		#endregion
	}

}
