//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace netcoreFreesql.Models {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class OrderDetails {

		[JsonProperty, Column(IsPrimary = true)]
		public int OrderID { get; set; }

		[JsonProperty]
		public int ProductID { get; set; }

		[JsonProperty, Column(DbType = "MONEY")]
		public string UnitPrice { get; set; }

		[JsonProperty]
		public short Quantity { get; set; }

		[JsonProperty, Column(DbType = "REAL")]
		public float Discount { get; set; }


		#region 外键 => 导航属性，ManyToMany

		#endregion
	}

}
