//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace netcoreFreesql.Models {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class Orders {

		[JsonProperty, Column(IsPrimary = true)]
		public int OrderID { get; set; }

		[JsonProperty, Column(DbType = "NCHAR(5)")]
		public string CustomerID { get => _CustomerID; set {
			if (_CustomerID == value) return;
			_CustomerID = value;
			Customers = null;
		} }
		private string _CustomerID;

		[JsonProperty]
		public int? EmployeeID { get; set; }

		[JsonProperty]
		public DateTime? OrderDate { get; set; }

		[JsonProperty]
		public DateTime? RequiredDate { get; set; }

		[JsonProperty]
		public DateTime? ShippedDate { get; set; }

		[JsonProperty, Column(DbType = "MONEY")]
		public string Freight { get; set; }

		[JsonProperty, Column(DbType = "NVARCHAR(40)")]
		public string ShipName { get; set; }

		[JsonProperty, Column(DbType = "NVARCHAR(60)")]
		public string ShipAddress { get; set; }

		[JsonProperty, Column(DbType = "NVARCHAR(15)")]
		public string ShipCity { get; set; }

		[JsonProperty, Column(DbType = "NVARCHAR(15)")]
		public string ShipRegion { get; set; }

		[JsonProperty, Column(DbType = "NVARCHAR(10)")]
		public string ShipPostalCode { get; set; }

		[JsonProperty, Column(DbType = "NVARCHAR(15)")]
		public string ShipCountry { get; set; }


		#region 外键 => 导航属性，ManyToOne/OneToOne

		[Navigate("CustomerID")]
		public virtual Customers Customers { get; set; }

		#endregion

		#region 外键 => 导航属性，ManyToMany

		#endregion
	}

}
