//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace netcoreFreesql.Models {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class Products {

		[JsonProperty, Column(IsPrimary = true)]
		public int ProductID { get; set; }

		[JsonProperty]
		public int? SupplierID { get => _SupplierID; set {
			if (_SupplierID == value) return;
			_SupplierID = value;
			Suppliers = null;
		} }
		private int? _SupplierID;

		[JsonProperty, Column(DbType = "NVARCHAR(40)")]
		public string ProductName { get; set; }

		[JsonProperty]
		public int? CategoryID { get; set; }

		[JsonProperty, Column(DbType = "NVARCHAR(20)")]
		public string QuantityPerUnit { get; set; }

		[JsonProperty, Column(DbType = "MONEY")]
		public string UnitPrice { get; set; }

		[JsonProperty]
		public short? UnitsInStock { get; set; }

		[JsonProperty]
		public short? UnitsOnOrder { get; set; }

		[JsonProperty]
		public short? ReorderLevel { get; set; }

		[JsonProperty, Column(DbType = "BIT")]
		public string Discontinued { get; set; }

		[JsonProperty]
		public DateTime? DiscontinuedDate { get; set; }


		#region 外键 => 导航属性，ManyToOne/OneToOne

		[Navigate("SupplierID")]
		public virtual Suppliers Suppliers { get; set; }

		#endregion

		#region 外键 => 导航属性，ManyToMany

		#endregion
	}

}
